from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol

from app.domain.models import (
    ConversationMessage,
    GraphFact,
    InvestorPersona,
    ResearchConversation,
    ResearchNote,
    SourceDocument,
    Stock,
)


class ResearchRepository(Protocol):
    async def initialize(self) -> None: ...

    async def healthcheck(self) -> bool: ...

    def ticker_lock(self, ticker: str) -> AbstractAsyncContextManager[None]: ...

    async def upsert_stock(self, stock: Stock) -> None: ...

    async def get_stock(self, ticker: str) -> Stock | None: ...

    async def follow_stock(self, user_id: str, ticker: str) -> bool: ...

    async def unfollow_stock(self, user_id: str, ticker: str) -> bool: ...

    async def list_followed_tickers(
        self, user_id: str | None = None
    ) -> tuple[str, ...]: ...

    async def list_stocks_for_user(self, user_id: str) -> tuple[Stock, ...]: ...

    async def list_all_stocks(self) -> tuple[Stock, ...]: ...

    async def has_document_hash(self, ticker: str, content_hash: str) -> bool: ...

    async def insert_document(
        self, document: SourceDocument, embedding: tuple[float, ...]
    ) -> bool: ...

    async def upsert_document(
        self, document: SourceDocument, embedding: tuple[float, ...]
    ) -> bool: ...

    async def count_documents(self, ticker: str) -> int: ...

    async def list_documents(
        self, ticker: str | None = None
    ) -> tuple[SourceDocument, ...]: ...

    async def deduplicate_documents(self, ticker: str | None = None) -> int: ...

    async def upsert_graph_facts(self, facts: tuple[GraphFact, ...]) -> None: ...

    async def list_graph_facts(self, ticker: str) -> tuple[GraphFact, ...]: ...

    async def search_documents(
        self,
        query_embedding: tuple[float, ...],
        *,
        tickers: tuple[str, ...],
        limit: int,
    ) -> tuple[SourceDocument, ...]: ...

    async def get_persona(self, user_id: str) -> InvestorPersona: ...

    async def save_persona(
        self, persona: InvestorPersona, embedding: tuple[float, ...]
    ) -> None: ...

    async def upsert_user(
        self, user_id: str, email: str, name: str | None, picture: str | None
    ) -> None: ...

    async def get_user(self, user_id: str) -> dict[str, str | None] | None: ...

    async def list_users(self) -> tuple[dict[str, str | None], ...]: ...

    async def reset_user_profile(self, user_id: str) -> bool: ...

    async def reset_user_follows(self, user_id: str) -> bool: ...

    async def delete_user_conversations(self, user_id: str) -> bool: ...

    async def create_session(
        self, session_id: str, user_id: str, expires_at: float
    ) -> None: ...

    async def get_session_user(self, session_id: str, now: float) -> str | None: ...

    async def delete_session(self, session_id: str) -> None: ...

    async def create_conversation(self, conversation: ResearchConversation) -> None: ...

    async def list_conversations(self, user_id: str) -> tuple[ResearchConversation, ...]: ...

    async def get_conversation(
        self, user_id: str, conversation_id: str
    ) -> ResearchConversation | None: ...

    async def update_conversation(self, conversation: ResearchConversation) -> None: ...

    async def add_conversation_message(self, message: ConversationMessage) -> None: ...

    async def list_conversation_messages(
        self, user_id: str, conversation_id: str
    ) -> tuple[ConversationMessage, ...]: ...

    async def create_note(self, note: ResearchNote) -> None: ...

    async def list_notes(self, user_id: str) -> tuple[ResearchNote, ...]: ...

    async def get_note(self, user_id: str, note_id: str) -> ResearchNote | None: ...

    async def update_note(self, note: ResearchNote) -> None: ...

    async def delete_note(self, user_id: str, note_id: str) -> bool: ...
